{
 "title": "Platform_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Online status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Total RAM memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes{host=\"$host\"}[$__range]) / 1024 / 1024 / 1024",
     "legendFormat": "Host: {{host}}"
    }
   ]
  },
  {
   "title": "Total storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(node_filesystem_size_bytes{host=\"$host\"}[$__range])) / 1024 / 1024 / 1024\r\n"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", host=\"$host\"}[2m])))"
    }
   ]
  },
  {
   "title": "RAM utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (\r\n  (avg_over_time(node_memory_MemFree_bytes{host=\"$host\"}[$__range]) +\r\n   avg_over_time(node_memory_Cached_bytes{host=\"$host\"}[$__range]) +\r\n   avg_over_time(node_memory_Buffers_bytes{host=\"$host\"}[$__range]))\r\n  / avg_over_time(node_memory_MemTotal_bytes{host=\"$host\"}[$__range])\r\n))"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(node_filesystem_avail_bytes{host=\"$host\", fstype!~\"tmpfs|overlay\"}[$__range])) / 1024 / 1024 / 1024\r\n",
     "legendFormat": "Available space"
    },
    {
     "expr": "sum(\r\n  avg_over_time(node_filesystem_size_bytes{host=\"$host\", fstype!~\"tmpfs|overlay\"}[$__range])\r\n  - avg_over_time(node_filesystem_free_bytes{host=\"$host\", fstype!~\"tmpfs|overlay\"}[$__range])\r\n) / 1024 / 1024 / 1024\r\n",
     "legendFormat": "Used space"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (\r\n  (avg_over_time(node_memory_MemFree_bytes{host=\"$host\"}[$__range]) +\r\n   avg_over_time(node_memory_Cached_bytes{host=\"$host\"}[$__range]) +\r\n   avg_over_time(node_memory_Buffers_bytes{host=\"$host\"}[$__range]))\r\n  / avg_over_time(node_memory_MemTotal_bytes{host=\"$host\"}[$__range])\r\n))",
     "legendFormat": "Host: {{host}}"
    }
   ]
  },
  {
   "title": "CPU utilization diagram",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", host=\"$host\"}[$__range])))",
     "legendFormat": "CPU utilization"
    }
   ]
  }
 ]
}