"""Ansible playbook execution module."""

import asyncio
import json
import os
import time

import ansible_runner

from app.core import exceptions
from app.schemas import service_schemas


class AnsibleExecutor:
    """Class to handle the technical execution of Ansible playbooks.

    This executor manages the interaction with ansible_runner, handles dynamic
    inventory generation, and parses the resulting platform JSON reports
    stored on the file system.
    """

    REPORTS_DIR = "/code/ansible/platform_reports"
    PLAYBOOK_DIR = "/code/ansible"

    PLAYBOOK_MAP = {
        service_schemas.AnsiblePlaybook.create_user: f"{PLAYBOOK_DIR}/create_ansible_user.yaml",
        service_schemas.AnsiblePlaybook.scan_platform: f"{PLAYBOOK_DIR}/scan_platform.yaml",
        service_schemas.AnsiblePlaybook.deploy_agent: f"{PLAYBOOK_DIR}/deploy_agent.yaml",
        service_schemas.AnsiblePlaybook.delete_agent: f"{PLAYBOOK_DIR}/delete_agent.yaml",
        service_schemas.AnsiblePlaybook.delete_ansible: f"{PLAYBOOK_DIR}/delete_ansible.yaml",
    }

    @classmethod
    def parse_platform_report(cls, hostname: str) -> dict:
        """Reads and parses the JSON file generated by Ansible.

        This method extracts hardware and system information from a specific
        host's report file and maps it.

        :param hostname: The hostname of the machine whose report should be parsed.
        :return: A dictionary containing mapped system information (CPU, RAM, Disks, Network).
        """
        report_path = os.path.join(cls.REPORTS_DIR, f"{hostname}-platform-info.json")

        if not os.path.exists(report_path):
            raise exceptions.ObjectNotFoundError("Platform report", name=hostname)

        # Small delay to ensure the file system has finished writing the report
        time.sleep(1)
        try:
            with open(report_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            root_key = list(data.keys())[0]
            info = data[root_key]

            # TODO: for now ansible provides only one CPU in json - maybe we
            #  need to change discovery command or test it with platform with 2 CPUs,
            #  for now i leave it hardcoded
            cpu_info = info.get("cpu", {})
            cpu_str = f"{cpu_info.get('name', 'Unknown')} ({cpu_info.get('cores', '?')} cores)"
            cpu_list = [{"name": cpu_str}]

            ram_info = info.get("ram_memory", {})
            ram_str = f"{ram_info.get('real_gb', '?')}"

            drives = info.get("drives", [])
            disk_list = []
            for d in drives:
                disk_list.append(
                    {
                        "name": d.get("mount", "Unknown"),
                        "capacity": f'{d.get("size_gb", "?")}',
                    }
                )

            dist = info.get("distribution", {})
            os_str = f"{dist.get('name', 'Linux')} {dist.get('version', '')}"

            net = info.get("network", {})
            mac_address = net.get("mac")
            ip_address = net.get("ip")

            meta = info.get("metadata", {})
            has_node_exporter = meta.get("has_agent", False)

            return {
                "name": root_key,
                "os": os_str,
                "cpus": cpu_list,
                "ram": ram_str,
                "disks": disk_list,
                "mac_address": mac_address,
                "ip_address": ip_address,
                "agent_prometheus": has_node_exporter,
            }
        except Exception as e:
            raise exceptions.ValidationError(
                f"Error parsing platform report for host '{hostname}'"
            ) from e

    @classmethod
    async def run_playbook_task(
        cls, playbook_enum, host: str | list, extra_vars: dict
    ) -> dict:
        """Helper function to run an Ansible playbook dynamically.

        Runs the specified playbook using ansible_runner in a separate thread.

        :param playbook_enum: The AnsiblePlaybook enum value mapping to a YAML file.
        :param host: A single hostname string, a comma-separated string, or a list of hosts.
        :param extra_vars: Dictionary of variables to pass into the playbook.
        :return: A dictionary with the status and return code of the execution.
        """
        playbook_path = cls.PLAYBOOK_MAP[playbook_enum]

        if isinstance(host, str):
            hosts_list = [h.strip() for h in host.split(",") if h.strip()]
        else:
            hosts_list = host

        host_dict = {"all": {"hosts": {h: {} for h in hosts_list}}}
        hosts_display = ", ".join(hosts_list)

        def _run():
            return ansible_runner.run(
                playbook=playbook_path,
                inventory=host_dict,
                extravars=extra_vars,
            )

        try:
            r = await asyncio.to_thread(_run)
        except Exception as e:
            raise exceptions.ValidationError(
                f"Failed to initialize Ansible runner for hosts '{hosts_display}'"
            ) from e

        if r.rc != 0 or r.status != "successful":
            playbook_name = os.path.basename(playbook_path)
            raise exceptions.ValidationError(
                f"Ansible task '{playbook_name}' failed for hosts: {hosts_display}. "
                f"Status: {r.status}, Return Code: {r.rc}"
            )
        return {"status": r.status, "rc": r.rc}
