/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as User_dashboardRouteImport } from './routes/user_dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthLabsRouteImport } from './routes/_auth/labs'
import { Route as AuthImportExportRouteImport } from './routes/_auth/import-export'
import { Route as AuthHistoryRouteImport } from './routes/_auth/history'
import { Route as AuthDocsRouteImport } from './routes/_auth/docs'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthInventoryIndexRouteImport } from './routes/_auth/inventory/index'
import { Route as AuthDocsIndexRouteImport } from './routes/_auth/docs/index'
import { Route as AuthDocsDocIdRouteImport } from './routes/_auth/docs/$docId'
import { Route as AuthInventoryDeviceDeviceidRouteImport } from './routes/_auth/inventory/device/$deviceid'

const User_dashboardRoute = User_dashboardRouteImport.update({
  id: '/user_dashboard',
  path: '/user_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLabsRoute = AuthLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthImportExportRoute = AuthImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHistoryRoute = AuthHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDocsRoute = AuthDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventoryIndexRoute = AuthInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDocsIndexRoute = AuthDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDocsRoute,
} as any)
const AuthDocsDocIdRoute = AuthDocsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => AuthDocsRoute,
} as any)
const AuthInventoryDeviceDeviceidRoute =
  AuthInventoryDeviceDeviceidRouteImport.update({
    id: '/inventory/device/$deviceid',
    path: '/inventory/device/$deviceid',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/user_dashboard': typeof User_dashboardRoute
  '/admin': typeof AuthAdminRoute
  '/docs': typeof AuthDocsRouteWithChildren
  '/history': typeof AuthHistoryRoute
  '/import-export': typeof AuthImportExportRoute
  '/labs': typeof AuthLabsRoute
  '/settings': typeof AuthSettingsRoute
  '/': typeof AuthIndexRoute
  '/docs/$docId': typeof AuthDocsDocIdRoute
  '/docs/': typeof AuthDocsIndexRoute
  '/inventory': typeof AuthInventoryIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/inventory/device/$deviceid': typeof AuthInventoryDeviceDeviceidRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/user_dashboard': typeof User_dashboardRoute
  '/admin': typeof AuthAdminRoute
  '/history': typeof AuthHistoryRoute
  '/import-export': typeof AuthImportExportRoute
  '/labs': typeof AuthLabsRoute
  '/settings': typeof AuthSettingsRoute
  '/': typeof AuthIndexRoute
  '/docs/$docId': typeof AuthDocsDocIdRoute
  '/docs': typeof AuthDocsIndexRoute
  '/inventory': typeof AuthInventoryIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/inventory/device/$deviceid': typeof AuthInventoryDeviceDeviceidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/user_dashboard': typeof User_dashboardRoute
  '/_auth/admin': typeof AuthAdminRoute
  '/_auth/docs': typeof AuthDocsRouteWithChildren
  '/_auth/history': typeof AuthHistoryRoute
  '/_auth/import-export': typeof AuthImportExportRoute
  '/_auth/labs': typeof AuthLabsRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/docs/$docId': typeof AuthDocsDocIdRoute
  '/_auth/docs/': typeof AuthDocsIndexRoute
  '/_auth/inventory/': typeof AuthInventoryIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/inventory/device/$deviceid': typeof AuthInventoryDeviceDeviceidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/user_dashboard'
    | '/admin'
    | '/docs'
    | '/history'
    | '/import-export'
    | '/labs'
    | '/settings'
    | '/'
    | '/docs/$docId'
    | '/docs/'
    | '/inventory'
    | '/users'
    | '/inventory/device/$deviceid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/user_dashboard'
    | '/admin'
    | '/history'
    | '/import-export'
    | '/labs'
    | '/settings'
    | '/'
    | '/docs/$docId'
    | '/docs'
    | '/inventory'
    | '/users'
    | '/inventory/device/$deviceid'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/user_dashboard'
    | '/_auth/admin'
    | '/_auth/docs'
    | '/_auth/history'
    | '/_auth/import-export'
    | '/_auth/labs'
    | '/_auth/settings'
    | '/_auth/'
    | '/_auth/docs/$docId'
    | '/_auth/docs/'
    | '/_auth/inventory/'
    | '/_auth/users/'
    | '/_auth/inventory/device/$deviceid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  User_dashboardRoute: typeof User_dashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user_dashboard': {
      id: '/user_dashboard'
      path: '/user_dashboard'
      fullPath: '/user_dashboard'
      preLoaderRoute: typeof User_dashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/labs': {
      id: '/_auth/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof AuthLabsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/import-export': {
      id: '/_auth/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof AuthImportExportRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/history': {
      id: '/_auth/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthHistoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/docs': {
      id: '/_auth/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthDocsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventory/': {
      id: '/_auth/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthInventoryIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/docs/': {
      id: '/_auth/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof AuthDocsIndexRouteImport
      parentRoute: typeof AuthDocsRoute
    }
    '/_auth/docs/$docId': {
      id: '/_auth/docs/$docId'
      path: '/$docId'
      fullPath: '/docs/$docId'
      preLoaderRoute: typeof AuthDocsDocIdRouteImport
      parentRoute: typeof AuthDocsRoute
    }
    '/_auth/inventory/device/$deviceid': {
      id: '/_auth/inventory/device/$deviceid'
      path: '/inventory/device/$deviceid'
      fullPath: '/inventory/device/$deviceid'
      preLoaderRoute: typeof AuthInventoryDeviceDeviceidRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthDocsRouteChildren {
  AuthDocsDocIdRoute: typeof AuthDocsDocIdRoute
  AuthDocsIndexRoute: typeof AuthDocsIndexRoute
}

const AuthDocsRouteChildren: AuthDocsRouteChildren = {
  AuthDocsDocIdRoute: AuthDocsDocIdRoute,
  AuthDocsIndexRoute: AuthDocsIndexRoute,
}

const AuthDocsRouteWithChildren = AuthDocsRoute._addFileChildren(
  AuthDocsRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRoute
  AuthDocsRoute: typeof AuthDocsRouteWithChildren
  AuthHistoryRoute: typeof AuthHistoryRoute
  AuthImportExportRoute: typeof AuthImportExportRoute
  AuthLabsRoute: typeof AuthLabsRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthInventoryIndexRoute: typeof AuthInventoryIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
  AuthInventoryDeviceDeviceidRoute: typeof AuthInventoryDeviceDeviceidRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRoute,
  AuthDocsRoute: AuthDocsRouteWithChildren,
  AuthHistoryRoute: AuthHistoryRoute,
  AuthImportExportRoute: AuthImportExportRoute,
  AuthLabsRoute: AuthLabsRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthInventoryIndexRoute: AuthInventoryIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
  AuthInventoryDeviceDeviceidRoute: AuthInventoryDeviceDeviceidRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  User_dashboardRoute: User_dashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
