import os
import json
import asyncio

import ansible_runner
from fastapi import  HTTPException


from app.database import get_db
from app.db.models import Machines, Metadata, Rooms

REPORTS_DIR = "./platform_reports"
PLAYBOOK_DIR = "/code/ansible"

def parse_platform_report(hostname: str) -> dict:
    """
     Reads and parses the JSON file generated by Ansible.
     Returns a dictionary matching the Machines model.
     """
    report_path = os.path.join(REPORTS_DIR, f"{hostname}-platform-info.json")


    if not os.path.exists(report_path):
        raise FileNotFoundError(
            f"Report not found for {hostname} at {report_path}"
        )

    try:
        with open(report_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        root_key = list(data.keys())[0]
        info = data[root_key]

        cpu_info = info.get("cpu", {})
        cpu_str = (
            f"{cpu_info.get('name', 'Unknown')} "
            f"({cpu_info.get('cores', '?')} cores)"
        )

        ram_info = info.get("ram_memory", {})
        ram_str = f"{ram_info.get('real_gb', '?')} GB"

        drives = info.get("drives", [])
        disk_list = []
        for d in drives:
            size_gb = d.get("size_gb", "?")
            mount = d.get("mount", "?")
            disk_list.append(f"{mount} ({size_gb}GB)")
        disk_str = ", ".join(disk_list) if disk_list else "Unknown"

        dist = info.get("distribution", {})
        os_str = f"{dist.get('name', 'Linux')} {dist.get('version', '')}"

        net = info.get("network", {})
        mac_address = net.get("mac")
        ip_address = net.get("ip")

        meta = info.get("metadata", {})
        has_node_exporter = meta.get("has_agent", False)

        return {
            "os": os_str,
            "cpu": cpu_str,
            "ram": ram_str,
            "disk": disk_str,
            "mac_address": mac_address,
            "ip_address": ip_address,
            "agent_prometheus": has_node_exporter,
        }

    except Exception as e:
        raise ValueError(
            f"Error parsing report for {hostname}: {str(e)}"
        ) from e


async def run_playbook_task(
    playbook_name: str, inventory: list | str, extra_vars: dict
):
    """
    Wrapper for ansible_runner running in a separate thread to avoid blocking API.
    """

    if isinstance(inventory, list):
        hosts_str = ",".join(inventory)
        if len(inventory) > 0 and not hosts_str.endswith(","):
            hosts_str += ","
    else:
        hosts_str = inventory
        if not hosts_str.endswith(","):
            hosts_str += ","

    def _run():
        return ansible_runner.run(
            private_data_dir="/code",
            playbook=os.path.join(PLAYBOOK_DIR, playbook_name),
            inventory=hosts_str,
            extravars=extra_vars,
            quiet=True,
        )

    runner = await asyncio.to_thread(_run)

    if runner.rc != 0:
        raise HTTPException(
            status_code=500,
            detail=f"Ansible execution failed. RC: {runner.rc}",
        )
    return runner